# Generated by Django 5.0.6 on 2024-06-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('FC', 'FreeCourse'), ('PC', 'PremiumCourse')], max_length=2)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
    ]
